language: node_js
sudo: false
dist: trusty
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
- TEST_SUITE=lint
- TEST_SUITE=test
script: npm run $TEST_SUITE
before_deploy: npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: ux@dbc.dk
  api_key:
    secure: TfzAvA4HhVUeqW4Cq3wyD3UapFgpk41BRELglIDR0lWDlY5s7Pu22Dpt9qmOhLyLFQD+IqyIYgbd8TPQM9ZnWkqAAHXvwSca1S5+4bnVL8dnVxTjz8BWUSkkS19R22GBk737uPRCHZ/+2J3VHQU1eWGZ1+jSeUWejZVPBfLS9Nt7JSEVmqWoUZlRSq16qlClcL2enIuLp5P9dKkCRTdvVRffsLybiVgS0Vm+9cz1NsBXV8QdB/2Hvxu9u0VJi4VLdeupmrVMFictLxdBB40QtPfZ1a2VQpPwHsE0P+7eZWLJPYdkImqtGymJ6jBFhqC0+rJZCB6ScJ82uoxelfsgnFxFyP40cVGOtoNMxttUrKMMKT5nxgURUpx3RfKT2wqYgGrW+l5qwXEERQ3imYBUlgN/wZtgJrFGVGk4McxUsEQJDHj0y2FyUZ1PLPLNXhHtxAkPZJfHdirUYZUZ0iGjHqQlKNoBpRKiG7pNmMABCMqDA4JskXK25I9mVMsTN81MdpnH+HlDxvoX6jkcDFBbPU4Vbgg1QMuluGviB1h+boGIshgVdccM6EPK6t7T9DI+2D6H2yJXPlZ+Mp2KtAdMxvgahajsjdQfkbF8GdwgohdiRa2DhHcLkk0hpLFfmeHqRM+dq+nxeMD/cJoHDpQwGwYv6s1+YlUOfVoFvid1EFc=
  on:
    tags: false
    branch: master
    repo: DBCDK/passport-unilogin
